import React, { Component } from 'react';

import logo from '../../assets/logo.png';
import { Container, Form } from './style';
import CompareList from '../../components/compareList/index';

export default class Main extends Component {
  state = {
    repositories: [
      {
        id: 10270250,
        node_id: 'MDEwOlJlcG9zaXRvcnkxMDI3MDI1MA==',
        name: 'react',
        full_name: 'facebook/react',
        private: false,
        owner: {
          login: 'facebook',
          id: 69631,
          node_id: 'MDEyOk9yZ2FuaXphdGlvbjY5NjMx',
          avatar_url: 'https://avatars3.githubusercontent.com/u/69631?v=4',
          gravatar_id: '',
          url: 'https://api.github.com/users/facebook',
          html_url: 'https://github.com/facebook',
          followers_url: 'https://api.github.com/users/facebook/followers',
          following_url: 'https://api.github.com/users/facebook/following{/other_user}',
          gists_url: 'https://api.github.com/users/facebook/gists{/gist_id}',
          starred_url: 'https://api.github.com/users/facebook/starred{/owner}{/repo}',
          subscriptions_url: 'https://api.github.com/users/facebook/subscriptions',
          organizations_url: 'https://api.github.com/users/facebook/orgs',
          repos_url: 'https://api.github.com/users/facebook/repos',
          events_url: 'https://api.github.com/users/facebook/events{/privacy}',
          received_events_url: 'https://api.github.com/users/facebook/received_events',
          type: 'Organization',
          site_admin: false,
        },
        html_url: 'https://github.com/facebook/react',
        description:
          'A declarative, efficient, and flexible JavaScript library for building user interfaces.',
        fork: false,
        url: 'https://api.github.com/repos/facebook/react',
        forks_url: 'https://api.github.com/repos/facebook/react/forks',
        keys_url: 'https://api.github.com/repos/facebook/react/keys{/key_id}',
        collaborators_url:
          'https://api.github.com/repos/facebook/react/collaborators{/collaborator}',
        teams_url: 'https://api.github.com/repos/facebook/react/teams',
        hooks_url: 'https://api.github.com/repos/facebook/react/hooks',
        issue_events_url: 'https://api.github.com/repos/facebook/react/issues/events{/number}',
        events_url: 'https://api.github.com/repos/facebook/react/events',
        assignees_url: 'https://api.github.com/repos/facebook/react/assignees{/user}',
        branches_url: 'https://api.github.com/repos/facebook/react/branches{/branch}',
        tags_url: 'https://api.github.com/repos/facebook/react/tags',
        blobs_url: 'https://api.github.com/repos/facebook/react/git/blobs{/sha}',
        git_tags_url: 'https://api.github.com/repos/facebook/react/git/tags{/sha}',
        git_refs_url: 'https://api.github.com/repos/facebook/react/git/refs{/sha}',
        trees_url: 'https://api.github.com/repos/facebook/react/git/trees{/sha}',
        statuses_url: 'https://api.github.com/repos/facebook/react/statuses/{sha}',
        languages_url: 'https://api.github.com/repos/facebook/react/languages',
        stargazers_url: 'https://api.github.com/repos/facebook/react/stargazers',
        contributors_url: 'https://api.github.com/repos/facebook/react/contributors',
        subscribers_url: 'https://api.github.com/repos/facebook/react/subscribers',
        subscription_url: 'https://api.github.com/repos/facebook/react/subscription',
        commits_url: 'https://api.github.com/repos/facebook/react/commits{/sha}',
        git_commits_url: 'https://api.github.com/repos/facebook/react/git/commits{/sha}',
        comments_url: 'https://api.github.com/repos/facebook/react/comments{/number}',
        issue_comment_url: 'https://api.github.com/repos/facebook/react/issues/comments{/number}',
        contents_url: 'https://api.github.com/repos/facebook/react/contents/{+path}',
        compare_url: 'https://api.github.com/repos/facebook/react/compare/{base}...{head}',
        merges_url: 'https://api.github.com/repos/facebook/react/merges',
        archive_url: 'https://api.github.com/repos/facebook/react/{archive_format}{/ref}',
        downloads_url: 'https://api.github.com/repos/facebook/react/downloads',
        issues_url: 'https://api.github.com/repos/facebook/react/issues{/number}',
        pulls_url: 'https://api.github.com/repos/facebook/react/pulls{/number}',
        milestones_url: 'https://api.github.com/repos/facebook/react/milestones{/number}',
        notifications_url:
          'https://api.github.com/repos/facebook/react/notifications{?since,all,participating}',
        labels_url: 'https://api.github.com/repos/facebook/react/labels{/name}',
        releases_url: 'https://api.github.com/repos/facebook/react/releases{/id}',
        deployments_url: 'https://api.github.com/repos/facebook/react/deployments',
        created_at: '2013-05-24T16:15:54Z',
        updated_at: '2019-03-07T20:32:34Z',
        pushed_at: '2019-03-07T20:34:59Z',
        git_url: 'git://github.com/facebook/react.git',
        ssh_url: 'git@github.com:facebook/react.git',
        clone_url: 'https://github.com/facebook/react.git',
        svn_url: 'https://github.com/facebook/react',
        homepage: 'https://reactjs.org',
        size: 140963,
        stargazers_count: 123871,
        watchers_count: 123871,
        language: 'JavaScript',
        has_issues: true,
        has_projects: true,
        has_downloads: true,
        has_wiki: true,
        has_pages: true,
        forks_count: 22487,
        mirror_url: null,
        archived: false,
        open_issues_count: 569,
        license: {
          key: 'mit',
          name: 'MIT License',
          spdx_id: 'MIT',
          url: 'https://api.github.com/licenses/mit',
          node_id: 'MDc6TGljZW5zZTEz',
        },
        forks: 22487,
        open_issues: 569,
        watchers: 123871,
        default_branch: 'master',
        organization: {
          login: 'facebook',
          id: 69631,
          node_id: 'MDEyOk9yZ2FuaXphdGlvbjY5NjMx',
          avatar_url: 'https://avatars3.githubusercontent.com/u/69631?v=4',
          gravatar_id: '',
          url: 'https://api.github.com/users/facebook',
          html_url: 'https://github.com/facebook',
          followers_url: 'https://api.github.com/users/facebook/followers',
          following_url: 'https://api.github.com/users/facebook/following{/other_user}',
          gists_url: 'https://api.github.com/users/facebook/gists{/gist_id}',
          starred_url: 'https://api.github.com/users/facebook/starred{/owner}{/repo}',
          subscriptions_url: 'https://api.github.com/users/facebook/subscriptions',
          organizations_url: 'https://api.github.com/users/facebook/orgs',
          repos_url: 'https://api.github.com/users/facebook/repos',
          events_url: 'https://api.github.com/users/facebook/events{/privacy}',
          received_events_url: 'https://api.github.com/users/facebook/received_events',
          type: 'Organization',
          site_admin: false,
        },
        network_count: 22487,
        subscribers_count: 6638,
      },
      {
        id: 1863329,
        node_id: 'MDEwOlJlcG9zaXRvcnkxODYzMzI5',
        name: 'laravel',
        full_name: 'laravel/laravel',
        private: false,
        owner: {
          login: 'laravel',
          id: 958072,
          node_id: 'MDEyOk9yZ2FuaXphdGlvbjk1ODA3Mg==',
          avatar_url: 'https://avatars3.githubusercontent.com/u/958072?v=4',
          gravatar_id: '',
          url: 'https://api.github.com/users/laravel',
          html_url: 'https://github.com/laravel',
          followers_url: 'https://api.github.com/users/laravel/followers',
          following_url: 'https://api.github.com/users/laravel/following{/other_user}',
          gists_url: 'https://api.github.com/users/laravel/gists{/gist_id}',
          starred_url: 'https://api.github.com/users/laravel/starred{/owner}{/repo}',
          subscriptions_url: 'https://api.github.com/users/laravel/subscriptions',
          organizations_url: 'https://api.github.com/users/laravel/orgs',
          repos_url: 'https://api.github.com/users/laravel/repos',
          events_url: 'https://api.github.com/users/laravel/events{/privacy}',
          received_events_url: 'https://api.github.com/users/laravel/received_events',
          type: 'Organization',
          site_admin: false,
        },
        html_url: 'https://github.com/laravel/laravel',
        description: 'A PHP framework for web artisans',
        fork: false,
        url: 'https://api.github.com/repos/laravel/laravel',
        forks_url: 'https://api.github.com/repos/laravel/laravel/forks',
        keys_url: 'https://api.github.com/repos/laravel/laravel/keys{/key_id}',
        collaborators_url:
          'https://api.github.com/repos/laravel/laravel/collaborators{/collaborator}',
        teams_url: 'https://api.github.com/repos/laravel/laravel/teams',
        hooks_url: 'https://api.github.com/repos/laravel/laravel/hooks',
        issue_events_url: 'https://api.github.com/repos/laravel/laravel/issues/events{/number}',
        events_url: 'https://api.github.com/repos/laravel/laravel/events',
        assignees_url: 'https://api.github.com/repos/laravel/laravel/assignees{/user}',
        branches_url: 'https://api.github.com/repos/laravel/laravel/branches{/branch}',
        tags_url: 'https://api.github.com/repos/laravel/laravel/tags',
        blobs_url: 'https://api.github.com/repos/laravel/laravel/git/blobs{/sha}',
        git_tags_url: 'https://api.github.com/repos/laravel/laravel/git/tags{/sha}',
        git_refs_url: 'https://api.github.com/repos/laravel/laravel/git/refs{/sha}',
        trees_url: 'https://api.github.com/repos/laravel/laravel/git/trees{/sha}',
        statuses_url: 'https://api.github.com/repos/laravel/laravel/statuses/{sha}',
        languages_url: 'https://api.github.com/repos/laravel/laravel/languages',
        stargazers_url: 'https://api.github.com/repos/laravel/laravel/stargazers',
        contributors_url: 'https://api.github.com/repos/laravel/laravel/contributors',
        subscribers_url: 'https://api.github.com/repos/laravel/laravel/subscribers',
        subscription_url: 'https://api.github.com/repos/laravel/laravel/subscription',
        commits_url: 'https://api.github.com/repos/laravel/laravel/commits{/sha}',
        git_commits_url: 'https://api.github.com/repos/laravel/laravel/git/commits{/sha}',
        comments_url: 'https://api.github.com/repos/laravel/laravel/comments{/number}',
        issue_comment_url: 'https://api.github.com/repos/laravel/laravel/issues/comments{/number}',
        contents_url: 'https://api.github.com/repos/laravel/laravel/contents/{+path}',
        compare_url: 'https://api.github.com/repos/laravel/laravel/compare/{base}...{head}',
        merges_url: 'https://api.github.com/repos/laravel/laravel/merges',
        archive_url: 'https://api.github.com/repos/laravel/laravel/{archive_format}{/ref}',
        downloads_url: 'https://api.github.com/repos/laravel/laravel/downloads',
        issues_url: 'https://api.github.com/repos/laravel/laravel/issues{/number}',
        pulls_url: 'https://api.github.com/repos/laravel/laravel/pulls{/number}',
        milestones_url: 'https://api.github.com/repos/laravel/laravel/milestones{/number}',
        notifications_url:
          'https://api.github.com/repos/laravel/laravel/notifications{?since,all,participating}',
        labels_url: 'https://api.github.com/repos/laravel/laravel/labels{/name}',
        releases_url: 'https://api.github.com/repos/laravel/laravel/releases{/id}',
        deployments_url: 'https://api.github.com/repos/laravel/laravel/deployments',
        created_at: '2011-06-08T03:06:08Z',
        updated_at: '2019-03-08T18:41:15Z',
        pushed_at: '2019-03-08T14:03:31Z',
        git_url: 'git://github.com/laravel/laravel.git',
        ssh_url: 'git@github.com:laravel/laravel.git',
        clone_url: 'https://github.com/laravel/laravel.git',
        svn_url: 'https://github.com/laravel/laravel',
        homepage: 'https://laravel.com',
        size: 9750,
        stargazers_count: 50555,
        watchers_count: 50555,
        language: 'PHP',
        has_issues: false,
        has_projects: true,
        has_downloads: true,
        has_wiki: false,
        has_pages: false,
        forks_count: 15445,
        mirror_url: null,
        archived: false,
        open_issues_count: 27,
        license: null,
        forks: 15445,
        open_issues: 27,
        watchers: 50555,
        default_branch: 'master',
        organization: {
          login: 'laravel',
          id: 958072,
          node_id: 'MDEyOk9yZ2FuaXphdGlvbjk1ODA3Mg==',
          avatar_url: 'https://avatars3.githubusercontent.com/u/958072?v=4',
          gravatar_id: '',
          url: 'https://api.github.com/users/laravel',
          html_url: 'https://github.com/laravel',
          followers_url: 'https://api.github.com/users/laravel/followers',
          following_url: 'https://api.github.com/users/laravel/following{/other_user}',
          gists_url: 'https://api.github.com/users/laravel/gists{/gist_id}',
          starred_url: 'https://api.github.com/users/laravel/starred{/owner}{/repo}',
          subscriptions_url: 'https://api.github.com/users/laravel/subscriptions',
          organizations_url: 'https://api.github.com/users/laravel/orgs',
          repos_url: 'https://api.github.com/users/laravel/repos',
          events_url: 'https://api.github.com/users/laravel/events{/privacy}',
          received_events_url: 'https://api.github.com/users/laravel/received_events',
          type: 'Organization',
          site_admin: false,
        },
        network_count: 15445,
        subscribers_count: 4646,
      },
    ],
  };

  render() {
    const { repositories } = this.state;
    return (
      <Container>
        <img src={logo} alt="Github Compare logo" />
        <Form>
          <input type="text" placeholder="usuário/repositório" />
          <button type="submit">Ok</button>
        </Form>
        <CompareList repositories={repositories} />
      </Container>
    );
  }
}
